# Generated by Django 4.1.7 on 2023-03-28 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('en_name', models.CharField(max_length=255)),
                ('ru_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrammaticCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('en_name', models.CharField(max_length=255)),
                ('ru_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RootMorpheme',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparative_app.concept')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparative_app.language')),
            ],
        ),
        migrations.CreateModel(
            name='GrammaticValue',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('en_name', models.CharField(max_length=255)),
                ('ru_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comparative_app.grammaticcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AffixalMorpheme',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gram_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparative_app.grammaticvalue')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparative_app.language')),
            ],
        ),
    ]
