# Generated by Django 4.1.7 on 2023-03-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparative_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affixalmorpheme',
            name='gram_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comparative_app.grammaticvalue'),
        ),
    ]
