# Generated by Django 4.2 on 2023-04-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparative_app', '0002_alter_affixalmorpheme_gram_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affixalmorpheme',
            old_name='name',
            new_name='morph_name',
        ),
        migrations.AlterField(
            model_name='affixalmorpheme',
            name='gram_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affixal_morphemes', to='comparative_app.grammaticvalue'),
        ),
        migrations.AlterField(
            model_name='affixalmorpheme',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affixal_morphemes', to='comparative_app.language'),
        ),
    ]
