# Generated by Django 4.2 on 2023-04-14 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comparative_app', '0004_alter_rootmorpheme_concept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootmorpheme',
            old_name='name',
            new_name='root_name',
        ),
    ]
