# Generated by Django 4.2 on 2023-04-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comparative_app', '0005_rename_name_rootmorpheme_root_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rootmorpheme',
            name='concept',
        ),
        migrations.CreateModel(
            name='RootConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=128)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparative_app.concept')),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comparative_app.rootmorpheme')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='roots',
            field=models.ManyToManyField(through='comparative_app.RootConcept', to='comparative_app.rootmorpheme'),
        ),
    ]
